version: '3.2'
services:
  app:
    container_name: ficha-x-bot
    ports:
      - "80:8080"
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - app_net

networks:
  app_net:
    driver: bridge